export enum ErrorCode {
  // Authentication & Authorization
  UNAUTHORISED = "UNAUTHORISED",
  NO_REFRESH = "NO_REFRESH",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_NOT_ACTIVE = "TOKEN_NOT_ACTIVE",
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // User Management
  EMAIL_EXISTS = "EMAIL_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  NOT_FOUND = "NOT_FOUND",

  // Role Management
  // PERMISSION_DENIED = "PERMISSION_DENIED",
  // ROLE_EXISTS = "ROLE_EXISTS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",

  // System Errors
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  FORBIDDEN = "FORBIDDEN",

  // Workspace Management
  WORKSPACE_NAME_EXISTS = "WORKSPACE_NAME_EXISTS",
  WORKSPACE_MEMBER_EXISTS = "WORKSPACE_MEMBER_EXISTS",
  WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND",
}
