export enum ErrorCode {
  // Authentication & Authorization
  UNAUTHORISED = "UNAUTHORISED",
  NO_REFRESH = "NO_REFRESH",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_NOT_ACTIVE = "TOKEN_NOT_ACTIVE",
  
  // User Management
  EMAIL_EXISTS = "EMAIL_EXISTS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  
  // System Errors
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}